/**
 * Generate TypeScript types from OpenAPI schema with custom transforms.
 *
 * Uses openapi-typescript Node API with postTransform to fix JsonValue type.
 * openapi-typescript inlines recursive $refs, causing TS2502 errors.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SCHEMA_PATH = path.join(ROOT, "openapi.json");
const OUTPUT_PATH = path.join(ROOT, "src/types/generated.ts");

// Create the JsonValue type reference
const jsonValueRef = ts.factory.createTypeReferenceNode("JsonValue");

const ast = await openapiTS(new URL(`file://${SCHEMA_PATH}`), {
  postTransform(schemaObject, metadata) {
    // Replace JsonValue inline definition with reference to our manual type
    if (metadata.path?.endsWith("/JsonValue")) {
      return jsonValueRef;
    }
  },
});

// Prepend import for JsonValue
const importDecl = ts.factory.createImportDeclaration(
  undefined,
  ts.factory.createImportClause(
    false,
    undefined,
    ts.factory.createNamedImports([
      ts.factory.createImportSpecifier(
        false,
        undefined,
        ts.factory.createIdentifier("JsonValue"),
      ),
    ]),
  ),
  ts.factory.createStringLiteral("./json-value"),
);

const HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
`;

const output = HEADER + astToString([importDecl, ...ast]);
fs.writeFileSync(OUTPUT_PATH, output);
console.log(`Generated ${OUTPUT_PATH}`);
